[package]
name = "rust-code"
version = "0.1.0"
edition = "2021"

[dependencies]

# tonic build dependencies
# [build-dependencies]
# prost-build = "0.12.3"
# tonic-build = { version = "0.11", features = ["prost"] }
